language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - xyz@example.com

env:
    matrix:
        - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
    update_sdk: true
    components:
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs
    - build-tools-26.1.0
    - android-26

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    #system images
    - sys-img-armeabi-v7a-android-26

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - chmod +x gradlew      #Grand permissions
    - android list targets
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
      - echo no | avdmanager create avd --force -n test -k "system-images;android-19;default;armeabi-v7a"
      - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
      - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"